export { API_BASE } from '../config/api';

export const playerImages = {
  'alexander alekhine': '/assets/Players/AlexanderAlekhine.avif',
  'alexey sarana': '/assets/Players/AlexeySarana.jpg',
  'alireza firouzja': '/assets/Players/AlirezaFirouzja.jpg',
  'amin tabatabaei': '/assets/Players/AminTabatabaei.jpg',
  'anatoly karpov': '/assets/Players/AnatolyKarpov.png',
  'andrey esipenko': '/assets/Players/AndreyEsipenko.jpg',
  'anish giri': '/assets/Players/AnishGiri.jpeg',
  'aravindh chithambaram': '/assets/Players/AravindhChithambaram.jpeg',
  'arjun erigaisi': '/assets/Players/ArjunErigaisi.jpg',
  'awonder liang': '/assets/Players/AwonderLiang.jpeg',
  'aydin suleymanli': '/assets/Players/AydinSuleymanli.jpg',
  'garry kasparov': '/assets/Players/GaryKasparov.jpg',
  'gary kasparov': '/assets/Players/GaryKasparov.jpg',
  'bobby fischer': '/assets/Players/BobbyFischer.jpg',
  'bu xiangzhi': '/assets/Players/BuXiangzhi.jpg',
  'david anton guijarro': '/assets/Players/DavidAntonGuijarro.jpg',
  'david howell': '/assets/Players/DavidHowell.jpeg',
  'ding liren': '/assets/Players/DingLiren.webp',
  'dmitry andreikin': '/assets/Players/DmitryAndreikin.jpg',
  'emanuel lasker': '/assets/Players/EmanuelLasker.png',
  'fabiano caruana': '/assets/Players/FabianoCaruana.png',
  'gukesh dommaraju': '/assets/Players/GukeshDommaraju.jpg',
  'hans niemann': '/assets/Players/HansNiemann.webp',
  'harikrishna pentala': '/assets/Players/HarikrishnaPentala.jpeg',
  'hikaru nakamura': '/assets/Players/HikaruNakamura.jpg',
  'ian nepomniachtchi': '/assets/Players/IanNepomniachtchi.jpg',
  'igor kovalenko': '/assets/Players/IgorKovalenko.avif',
  'ivan saric': '/assets/Players/IvanSaric.jpg',
  'jan-krzysztof duda': '/assets/Players/JanKrzysztofDuda.jpg',
  'jan krzysztof duda': '/assets/Players/JanKrzysztofDuda.jpg',
  'javokhir sindarov': '/assets/Players/JavokhirSindarov.webp',
  'jose raul capablanca': '/assets/Players/JoseRaulCapablanca.jpeg',
  'johan-sebastian christiansen': '/assets/Players/JohanSebastianChristiansen.jpg',
  'johan sebastian christiansen': '/assets/Players/JohanSebastianChristiansen.jpg',
  'jorden van foreest': '/assets/Players/JordenVanForeest.png',
  'kirill alekseenko': '/assets/Players/KirillAlekseenko.jpg',
  'le quang liem': '/assets/Players/LeQuangLiem.webp',
  'leinier dominguez perez': '/assets/Players/LeinierDominguez.jpg',
  'levon aronian': '/assets/Players/LevonAronian.jpg',
  'magnus carlsen': '/assets/Players/MagnusCarlsen.webp',
  'matthias bluebaum': '/assets/Players/MatthiasBluebaum.jpg',
  'maxime vachier-lagrave': '/assets/Players/MaximeVachierLagrave.jpg',
  'maxime vachier lagrave': '/assets/Players/MaximeVachierLagrave.jpg',
  'mikhail botvinnik': '/assets/Players/MikhailBotvinnik.jpg',
  'mikhail tal': '/assets/Players/MikhailTal.jpg',
  'nihal sarin': '/assets/Players/NihalSarin.jpg',
  'nikita vitiugov': '/assets/Players/NikitaVitiugov.jpg',
  'nils grandelius': '/assets/Players/NilsGrandelius.jpg',
  'nodirbek abdusattorov': '/assets/Players/NodirbekAbdusattorov.avif',
  'nodirbek yakubboev': '/assets/Players/NodirbekYakubboev.jpg',
  'parham maghsoodloo': '/assets/Players/ParhamMaghsoodloo.jpg',
  'pavel eljanov': '/assets/Players/PavelEljanov.jpg',
  'peter leko': '/assets/Players/PeterLeko.jpg',
  'peter svidler': '/assets/Players/PeterSvidler.jpg',
  'praggnanandhaa': '/assets/Players/Praggnanandhaa.webp',
  'praggnanandhaa rameshbabu': '/assets/Players/Praggnanandhaa.webp',
  'pranav venkatesh': '/assets/Players/PranavVenkatesh.jpg',
  'richard rapport': '/assets/Players/RichardRapport.jpg',
  'rustam kasimdzhanov': '/assets/Players/RustamKasimdzhanov.jpg',
  'sam sevian': '/assets/Players/SamSevian.jpg',
  'shakhriyar mamedyarov': '/assets/Players/ShakhriyarMamedyarov.jpg',
  'teimour radjabov': '/assets/Players/TeimourRadjabov.jpg',
  'veselin topalov': '/assets/Players/VeselinTopalov.jpg',
  'vidit gujrathi': '/assets/Players/ViditGujrathi.jpg',
  'vincent keymer': '/assets/Players/VincentKeymer.jpg',
  'viswanathan anand': '/assets/Players/ViswanathanAnand.webp',
  'vladimir fedoseev': '/assets/Players/VladimiFedoseev.jpg',
  'vladimir kramnik': '/assets/Players/VladimirKramnik.jpg',
  'wang hao': '/assets/Players/WangHao.webp',
  'wei yi': '/assets/Players/WeiYi.jpg',
  'wesley so': '/assets/Players/WesleySo.jpg',
  'yagiz kaan erdogmus': '/assets/Players/YagizKaanErdogmus.webp',
  'yu yangyi': '/assets/Players/YuYangyi.jpg',
};

export const playerFacts = {
  'magnus carlsen': {
    title: 'GM',
    fullName: 'Magnus Carlsen',
    born: 'Nov 30, 1990',
    birthplace: 'Tonsberg, Norway',
    federation: 'Norway',
    photoCredit: 'Photo: Maria Emelianova/Chess.com.',
  },
  'garry kasparov': {
    title: 'GM',
    fullName: 'Garry Kasparov',
    born: 'Apr 13, 1963',
    birthplace: 'Baku, Azerbaijan',
    federation: 'Russia',
  },
  'gary kasparov': {
    title: 'GM',
    fullName: 'Garry Kasparov',
    born: 'Apr 13, 1963',
    birthplace: 'Baku, Azerbaijan',
    federation: 'Russia',
  },
  'bobby fischer': {
    title: 'GM',
    fullName: 'Bobby Fischer',
    born: 'Mar 9, 1943',
    birthplace: 'Chicago, United States',
    federation: 'United States',
  },
  'hikaru nakamura': {
    title: 'GM',
    fullName: 'Hikaru Nakamura',
    born: 'Dec 9, 1987 (age 38)',
    birthplace: 'Hirakata, Japan',
    federation: 'United States',
  },
  'fabiano caruana': {
    title: 'GM',
    fullName: 'Fabiano Caruana',
    born: 'Jul 30, 1992',
    birthplace: 'Miami, United States',
    federation: 'United States',
  },
  'nodirbek abdusattorov': {
    title: 'GM',
    fullName: 'Nodirbek Abdusattorov',
    born: 'Sep 18, 2004',
    birthplace: 'Tashkent, Uzbekistan',
    federation: 'Uzbekistan',
  },
  'javokhir sindarov': {
    title: 'GM',
    fullName: 'Javokhir Sindarov',
    born: 'Dec 8, 2005',
    birthplace: 'Jizzakh, Uzbekistan',
    federation: 'Uzbekistan',
  },
  'anish giri': {
    title: 'GM',
    fullName: 'Anish Giri',
    born: 'Jun 28, 1994',
    birthplace: 'Saint Petersburg, Russia',
    federation: 'Netherlands',
  },
  'vincent keymer': {
    title: 'GM',
    fullName: 'Vincent Keymer',
    born: 'Nov 15, 2004',
    birthplace: 'Mainz, Germany',
    federation: 'Germany',
  },
  'alireza firouzja': {
    title: 'GM',
    fullName: 'Alireza Firouzja',
    born: 'Jun 18, 2003',
    birthplace: 'Babol, Iran',
    federation: 'France',
  },
  'wesley so': {
    title: 'GM',
    fullName: 'Wesley So',
    born: 'Oct 9, 1993',
    birthplace: 'Bacoor, Philippines',
    federation: 'United States',
  },
  'wei yi': {
    title: 'GM',
    fullName: 'Wei Yi',
    born: 'Jun 2, 1999',
    birthplace: 'Yancheng, China',
    federation: 'China',
  },
  'arjun erigaisi': {
    title: 'GM',
    fullName: 'Arjun Erigaisi',
    born: 'Sep 3, 2003',
    birthplace: 'Warangal, India',
    federation: 'India',
  },
  'hans niemann': {
    title: 'GM',
    fullName: 'Hans Niemann',
    born: 'Jun 20, 2003',
    birthplace: 'San Francisco, United States',
    federation: 'United States',
  },
  'jan krzysztof duda': {
    title: 'GM',
    fullName: 'Jan-Krzysztof Duda',
    born: 'Apr 26, 1998',
    birthplace: 'Krakow, Poland',
    federation: 'Poland',
  },
  'viswanathan anand': {
    title: 'GM',
    fullName: 'Viswanathan Anand',
    born: 'Dec 11, 1969',
    birthplace: 'Mayiladuthurai, India',
    federation: 'India',
  },
  'ding liren': {
    title: 'GM',
    fullName: 'Ding Liren',
    born: 'Oct 24, 1992',
    birthplace: 'Wenzhou, China',
    federation: 'China',
  },
  'jorden van foreest': {
    title: 'GM',
    fullName: 'Jorden van Foreest',
    born: 'Apr 30, 1999',
    birthplace: 'Utrecht, Netherlands',
    federation: 'Netherlands',
  },
  'praggnanandhaa rameshbabu': {
    title: 'GM',
    fullName: 'Praggnanandhaa Rameshbabu',
    born: 'Aug 10, 2005',
    birthplace: 'Chennai, India',
    federation: 'India',
  },
  'praggnanandhaa': {
    title: 'GM',
    fullName: 'Praggnanandhaa Rameshbabu',
    born: 'Aug 10, 2005',
    birthplace: 'Chennai, India',
    federation: 'India',
  },
  'gukesh dommaraju': {
    title: 'GM',
    fullName: 'Gukesh Dommaraju',
    born: 'May 29, 2006',
    birthplace: 'Chennai, India',
    federation: 'India',
  },
  'leinier dominguez perez': {
    title: 'GM',
    fullName: 'Leinier Dominguez Perez',
    born: 'Sep 23, 1983',
    birthplace: 'Havana, Cuba',
    federation: 'United States',
  },
  'le quang liem': {
    title: 'GM',
    fullName: 'Le Quang Liem',
    born: 'Mar 13, 1991',
    birthplace: 'Ho Chi Minh City, Vietnam',
    federation: 'Vietnam',
  },
  'richard rapport': {
    title: 'GM',
    fullName: 'Richard Rapport',
    born: 'Mar 25, 1996',
    birthplace: 'Szombathely, Hungary',
    federation: 'Romania',
  },
  'ian nepomniachtchi': {
    title: 'GM',
    fullName: 'Ian Nepomniachtchi',
    born: 'Jul 14, 1990',
    birthplace: 'Bryansk, Russia',
    federation: 'FIDE',
  },
  'levon aronian': {
    title: 'GM',
    fullName: 'Levon Aronian',
    born: 'Oct 6, 1982',
    birthplace: 'Yerevan, Armenia',
    federation: 'United States',
  },
  'nihal sarin': {
    title: 'GM',
    fullName: 'Nihal Sarin',
    born: 'Jul 13, 2004',
    birthplace: 'Thrissur, India',
    federation: 'India',
  },
  'shakhriyar mamedyarov': {
    title: 'GM',
    fullName: 'Shakhriyar Mamedyarov',
    born: 'Apr 12, 1985',
    birthplace: 'Sumqayit, Azerbaijan',
    federation: 'Azerbaijan',
  },
  'maxime vachier lagrave': {
    title: 'GM',
    fullName: 'Maxime Vachier-Lagrave',
    born: 'Oct 21, 1990',
    birthplace: 'Nogent-sur-Marne, France',
    federation: 'France',
  },
  'amin tabatabaei': {
    title: 'GM',
    fullName: 'Amin Tabatabaei',
    born: 'Feb 5, 2001',
    birthplace: 'Tehran, Iran',
    federation: 'Iran',
  },
  'yu yangyi': {
    title: 'GM',
    fullName: 'Yu Yangyi',
    born: 'Jun 8, 1994',
    birthplace: 'Huangshi, China',
    federation: 'China',
  },
  'parham maghsoodloo': {
    title: 'GM',
    fullName: 'Parham Maghsoodloo',
    born: 'Aug 11, 2000',
    birthplace: 'Gorgan, Iran',
    federation: 'Iran',
  },
  'dmitry andreikin': {
    title: 'GM',
    fullName: 'Dmitry Andreikin',
    born: 'Feb 5, 1990',
    birthplace: 'Ryazan, Russia',
    federation: 'FIDE',
  },
  'yagiz kaan erdogmus': {
    title: 'GM',
    fullName: 'Yagiz Kaan Erdogmus',
    born: 'Jun 3, 2011',
    birthplace: 'Bursa, Turkey',
    federation: 'Turkey',
  },
  'vidit gujrathi': {
    title: 'GM',
    fullName: 'Vidit Gujrathi',
    born: 'Oct 24, 1994',
    birthplace: 'Nashik, India',
    federation: 'India',
  },
  'awonder liang': {
    title: 'GM',
    fullName: 'Awonder Liang',
    born: 'Apr 9, 2003',
    birthplace: 'Madison, United States',
    federation: 'United States',
  },
  'vladimir fedoseev': {
    title: 'GM',
    fullName: 'Vladimir Fedoseev',
    born: 'Feb 16, 1995',
    birthplace: 'Saint Petersburg, Russia',
    federation: 'Slovenia',
  },
  'sam sevian': {
    title: 'GM',
    fullName: 'Sam Sevian',
    born: 'Dec 26, 2000',
    birthplace: 'Corning, United States',
    federation: 'United States',
  },
  'veselin topalov': {
    title: 'GM',
    fullName: 'Veselin Topalov',
    born: 'Mar 15, 1975',
    birthplace: 'Ruse, Bulgaria',
    federation: 'Bulgaria',
  },
  'matthias bluebaum': {
    title: 'GM',
    fullName: 'Matthias Bluebaum',
    born: 'Apr 18, 1997',
    birthplace: 'Lemgo, Germany',
    federation: 'Germany',
  },
  'aravindh chithambaram': {
    title: 'GM',
    fullName: 'Aravindh Chithambaram',
    born: 'Sep 11, 1999',
    birthplace: 'Chennai, India',
    federation: 'India',
  },
  'nodirbek yakubboev': {
    title: 'GM',
    fullName: 'Nodirbek Yakubboev',
    born: 'Jan 23, 2002',
    birthplace: 'Tashkent, Uzbekistan',
    federation: 'Uzbekistan',
  },
  'teimour radjabov': {
    title: 'GM',
    fullName: 'Teimour Radjabov',
    born: 'Mar 12, 1987',
    birthplace: 'Baku, Azerbaijan',
    federation: 'Azerbaijan',
  },
  'andrey esipenko': {
    title: 'GM',
    fullName: 'Andrey Esipenko',
    born: 'Mar 22, 2002',
    birthplace: 'Novocherkassk, Russia',
    federation: 'FIDE',
  },
  'wang hao': {
    title: 'GM',
    fullName: 'Wang Hao',
    born: 'Aug 4, 1989',
    birthplace: 'Harbin, China',
    federation: 'China',
  },
  'peter svidler': {
    title: 'GM',
    fullName: 'Peter Svidler',
    born: 'Jun 17, 1976',
    birthplace: 'Saint Petersburg, Russia',
    federation: 'FIDE',
  },
  'harikrishna pentala': {
    title: 'GM',
    fullName: 'Harikrishna Pentala',
    born: 'May 10, 1986',
    birthplace: 'Guntur, India',
    federation: 'India',
  },
  'peter leko': {
    title: 'GM',
    fullName: 'Peter Leko',
    born: 'Sep 8, 1979',
    birthplace: 'Subotica, Serbia',
    federation: 'Hungary',
  },
  'pavel eljanov': {
    title: 'GM',
    fullName: 'Pavel Eljanov',
    born: 'May 10, 1983',
    birthplace: 'Kharkiv, Ukraine',
    federation: 'Ukraine',
  },
  'igor kovalenko': {
    title: 'GM',
    fullName: 'Igor Kovalenko',
    born: 'Dec 29, 1988',
    birthplace: 'Novomoskovsk, Ukraine',
    federation: 'Ukraine',
  },
  'nikita vitiugov': {
    title: 'GM',
    fullName: 'Nikita Vitiugov',
    born: 'Feb 4, 1987',
    birthplace: 'Saint Petersburg, Russia',
    federation: 'England',
  },
  'aydin suleymanli': {
    title: 'GM',
    fullName: 'Aydin Suleymanli',
    born: 'Mar 22, 2005',
    birthplace: 'Baku, Azerbaijan',
    federation: 'Azerbaijan',
  },
  'david howell': {
    title: 'GM',
    fullName: 'David Howell',
    born: 'Nov 14, 1990',
    birthplace: 'Eastbourne, England',
    federation: 'England',
  },
  'rustam kasimdzhanov': {
    title: 'GM',
    fullName: 'Rustam Kasimdzhanov',
    born: 'Dec 5, 1979',
    birthplace: 'Tashkent, Uzbekistan',
    federation: 'Uzbekistan',
  },
  'alexey sarana': {
    title: 'GM',
    fullName: 'Alexey Sarana',
    born: 'Jan 26, 2000',
    birthplace: 'Moscow, Russia',
    federation: 'Serbia',
  },
  'nils grandelius': {
    title: 'GM',
    fullName: 'Nils Grandelius',
    born: 'Jun 3, 1993',
    birthplace: 'Lund, Sweden',
    federation: 'Sweden',
  },
  'bu xiangzhi': {
    title: 'GM',
    fullName: 'Bu Xiangzhi',
    born: 'Dec 10, 1985',
    birthplace: 'Qingdao, China',
    federation: 'China',
  },
  'pranav venkatesh': {
    title: 'GM',
    fullName: 'Pranav Venkatesh',
    born: 'Oct 13, 2006',
    birthplace: 'Chennai, India',
    federation: 'India',
  },
  'johan sebastian christiansen': {
    title: 'GM',
    fullName: 'Johan-Sebastian Christiansen',
    born: 'Jun 10, 1998',
    birthplace: 'Copenhagen, Denmark',
    federation: 'Norway',
  },
  'ivan saric': {
    title: 'GM',
    fullName: 'Ivan Saric',
    born: 'Aug 17, 1990',
    birthplace: 'Split, Croatia',
    federation: 'Croatia',
  },
  'david anton guijarro': {
    title: 'GM',
    fullName: 'David Anton Guijarro',
    born: 'Jun 23, 1995',
    birthplace: 'Madrid, Spain',
    federation: 'Spain',
  },
  'kirill alekseenko': {
    title: 'GM',
    fullName: 'Kirill Alekseenko',
    born: 'Jun 22, 1997',
    birthplace: 'Vyborg, Russia',
    federation: 'Austria',
  },
  'jose raul capablanca': {
    title: 'GM',
    fullName: 'Jose Raul Capablanca',
    born: 'Nov 19, 1888',
    birthplace: 'Havana, Cuba',
    federation: 'Cuba',
  },
  'anatoly karpov': {
    title: 'GM',
    fullName: 'Anatoly Karpov',
    born: 'May 23, 1951',
    birthplace: 'Zlatoust, Russia',
    federation: 'Russia',
  },
  'mikhail botvinnik': {
    title: 'GM',
    fullName: 'Mikhail Botvinnik',
    born: 'Aug 17, 1911',
    birthplace: 'Kuokkala, Finland',
    federation: 'Soviet Union',
  },
  'vladimir kramnik': {
    title: 'GM',
    fullName: 'Vladimir Kramnik',
    born: 'Jun 25, 1975',
    birthplace: 'Tuapse, Russia',
    federation: 'Russia',
  },
  'emanuel lasker': {
    title: 'GM',
    fullName: 'Emanuel Lasker',
    born: 'Dec 24, 1868',
    birthplace: 'Berlinchen, Prussia',
    federation: 'Germany',
  },
  'mikhail tal': {
    title: 'GM',
    fullName: 'Mikhail Tal',
    born: 'Nov 9, 1936',
    birthplace: 'Riga, Latvia',
    federation: 'Soviet Union',
  },
  'alexander alekhine': {
    title: 'GM',
    fullName: 'Alexander Alekhine',
    born: 'Oct 31, 1892',
    birthplace: 'Moscow, Russia',
    federation: 'France',
  },
};

export const latestComments = [
  'Le Quang Liem vs. Thanh Tu Tran, 2001',
  'Rasmus Svane vs. Wesley So, 2022',
  'Tihon Cherniaev vs. Wesley So, 2022',
  'Srinath Narayanan vs. Wesley So, 2022',
  'Mikhail Golubev vs. Wesley So, 2022',
];
